<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>
<div class="actions">
    <button id="ask-about-product"
            type="submit"
            class="action primary tocart"
            title="<?= $block->escapeHtmlAttr(__('Ask about this product')) ?>"
            data-mage-init='{"iuriis_askaboutthisproduct_askAboutProduct":{}}'
            style="margin-bottom: 20px; width: 49%; height: 49px; font-size: 1.5rem;">
        <span><?= $block->escapeHtml(__('Ask about this product')) ?></span>
    </button>
</div>