<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>
<div data-bind="scope:'chatBoxMessages'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
           "components": {
                "chatBoxMessages": {
                    "component": "iuriis_chatbox_chatBox"
                }
            }
        }
    }
}

</script>

