<?php /** @var \Iuriis\Chatbox\Block\ChatBox $block */ ?>
<div id="iuriis-chat-box"
     style="display: none;"
     data-mage-init='{"iuriis_chatbox_chatBox":{}}'>
    <div id="body-box-chat">
        <p class="message admin-message"> <?= $block->escapeHtml(__('Please, ask a questions!')) ?></p>
        <?php if ($block->getMessageCollection()->count()): ?>
            <ul class="chat-message-list">
                <?php /** @var \Iuriis\Chatbox\Model\Message $message */
                    foreach ($block->getMessageCollection() as $message) :
                ?>
                    <li class="chat-message <?= $block->escapeHtml($message->getAuthorType()) ?>">
                        <span class="date-time"><?= $block->escapeHtml($message->getCreatedAt()) ?></span>
                        <span class="message"><?= $block->escapeHtml($message->getMessage()) ?></span>
                    </li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>
    <div class="textarea-box-chat">
        <form action="javascript:void(0);"
              class="form"
              data-mage-init='{"iuriis_chatbox_form":{
                "action": "<?= $block->escapeUrl($block->getUrl('iuriis_chatbox/chatbox/save')) ?>"}}'
              id="iuriis-chat-box-form"
              method="post">
            <label for="user-message-question"></label>
            <textarea autofocus
                      data-validate="{required: true}"
                      id="user-message-question"
                      name="messages"
                      rows="1"
                      title="<?= $block->escapeHtmlAttr(__('Textarea')) ?>">
            </textarea>
            <input id="hideit" name="form_key" type="hidden" value="<?= $block->getBlockHtml('formkey')?>">
        </form>
    </div>
    <button type="submit" class="action primary" id="iuriis-chat-send-ask">
        <?= $block->escapeHtml(__('Send')) ?></button>
    <button type="button" id="iuriis-chat-close-chat-button">
        <?= $block->escapeHtml(__('Close')) ?></button>
</div>
