<?php /** @var \Iuriis\GeekhubController\Block\CustomBlock $block */ ?>
<div>
    <?php if ($block->getFirstName()): ?>
        <p>
            <?= $block->escapeHtml(__('First name: %1'), $block->getFirstName()) ?>
        </p>
    <?php endif;?>
    <?php if ($block->getLastName()): ?>
        <p>
            <?= $block->escapeHtml(__('Last name: %1'), $block->getLastName()) ?>
        </p>
    <?php endif;?>
</div>