<?php /**  @var \Iuriis\GeekhubController\Block\CustomBlock $block */ ?>
<div>
    <?php if ($block->getFirstName()): ?>
        <p>
            <?= $block->escapeHtml(__('First name: ')), $block->getFirstName() ?>
        </p>
    <?php endif;?>
    <?php if ($block->getLastName()): ?>
        <p>
            <?= $block->escapeHtml(__('Last name: ')), $block->getLastName() ?>
        </p>
    <?php endif;?>
</div>